<?php

$additionalInfo = $block->getPaymentAdditionalInformation();
?>

<?php if (!empty($additionalInfo['account_holder_name']) || !empty($additionalInfo['account_number'])): ?>
    <div class="box box-information">
        <strong><?php echo __('Additional Payment Information'); ?></strong>
        <br/>
        <?php if (!empty($additionalInfo['account_holder_name'])): ?>
            <div>
                <strong><?php echo __('Account Holder Name'); ?>:</strong>
                <?php echo htmlspecialchars($additionalInfo['account_holder_name'], ENT_QUOTES, 'UTF-8'); ?>
            </div>
        <?php endif; ?>
        <?php if (!empty($additionalInfo['account_number'])): ?>
            <div>
                <strong><?php echo __('Account Number'); ?>:</strong>
                <?php echo htmlspecialchars($additionalInfo['account_number'], ENT_QUOTES, 'UTF-8'); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
